#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/box ./files/box/etc/scripts/init
  cp ./scripts/r1 ./files/r1/etc/scripts/init
  cp ./scripts/r2 ./files/r2/etc/scripts/init
  cp ./scripts/faiservices ./files/faiservices/etc/scripts/init
  cp ./scripts/dns ./files/dns/etc/scripts/init
  cp ./scripts/web ./files/web/var/scripts/init
  cp ./scripts/ftp ./files/ftp/etc/scripts/init
  cp ./scripts/faiacces ./files/faiacces/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
