#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up
ip addr add 200.200.25.2/26 dev eth0
ip addr add 200.200.25.65/26 dev eth1

cd etc/quagga
service quagga restart
#telnet localhost ripd
#zebra
#en
#conf t
#router rip
#network 200.200.25.0/26
#network 200.200.25.64/26
cd /


